version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    image: faustis1337/search-engine-searchloadbalancer:latest
    ports:
      - 30016:80
  api-search:
    build:
      context: .
      dockerfile: "ApiSearch/Dockerfile"
    image: faustis1337/search-engine-api-search:latest
    deploy:
      replicas: 3
    depends_on:
      - load-balancer
  web-ui:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    image: faustis1337/search-engine-frontend:latest
    ports:
      - 9023:80

volumes:
  featurehub-h2-data: