apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
        - name: load-balancer
          image: faustis1337/search-engine-searchloadbalancer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: NodePort
  selector:
    app: load-balancer
  ports:
    - protocol: TCP
      port: 9020
      targetPort: 80
      nodePort: 30016