apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec:
  type: NodePort
  selector:
    app: load-balancer
  ports:
    - protocol: TCP
      port: 9020
      targetPort: 80
      nodePort: 30016