apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: searchapi-statefulset
spec:
  replicas: 3
  serviceName: searchapi-service
  selector:
    matchLabels:
      app: searchapi
  template:
    metadata:
      labels:
        app: searchapi
    spec:
      containers:
        - name: searchapi
          image: laszlo199/search-engine-api-search:7
          imagePullPolicy: Always 
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: searchapi-service
  namespace: default
spec:
  ports:
    - port: 8080
      name: web
  clusterIP: None
  selector:
    app: searchapi