version: '3.8'

services:
  receiverapi:
    build:
      context: ./receiver-api
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=receiverapi
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
    ports:
      - 8001:8080
  senderapi:
    build:
      context: ./sender-api
      dockerfile: Dockerfile
#    environment:
#      - OTEL_SERVICE_NAME=senderapi
#      - OTEL_METRICS_EXPORTER=prometheus
#      - OTEL_TRACES_EXPORTER=jaeger
#      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268
    ports:
      - 8002:80
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268"
      - "16686:16686"
      - "14250:14250"
      - "4318:4318"
      - "4317:4317"
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
  