version: '3.8'

services:
  receiverapi:
    build:
      context: .
      dockerfile: receiver-api/Dockerfile
    ports:
      - 8001:8080
#  senderapi:
#    build:
#      context: .
#      dockerfile: sender-api/Dockerfile
#    ports:
#      - 8002:80