version: '3.8'

services:
  receiverapi:
    build:
      context: ./receiver-api
      dockerfile: Dockerfile
    ports:
      - 8001:8080
  senderapi:
    build:
      context: ./sender-api
      dockerfile: Dockerfile
    ports:
      - 8002:80
#  jaeger-agent:
#    container_name: jaeger
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "6831:6831/udp"
#      - "14268:14268"
#      - "16686:16686"
#      - "4318:4318"
#      - "4317:4317"
#    networks:
#      - jaeger-example