version: '3.8'

services:
  receiverapi:
    build:
      context: ./receiver-api
      dockerfile: Dockerfile
    ports:
      - 8001:8080
  senderapi:
    build:
      context: ./sender-api
      dockerfile: Dockerfile
    ports:
      - 8002:80