global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'receiverapi'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['receiverapi:8080']
  - job_name: 'senderapi'
    static_configs:
      - targets: [ 'senderapi:80' ]